### ISSUE TITLE
Error is hidden if you leave trailing slash in AUTH0_DOMAIN 

### ISSUE THREAD

**Issue by lowlyocean** [DimiMikadze/fest#1]
If you include the trailing slash "/" in the AUTH0_DOMAIN as shown in [these instructions](https://github.com/DimiMikadze/fest/blob/1b17739d8c50c06efa5b14e1000f7ef92dbf4ca1/docs/auth0.md?plain=1#L15), all you will see is **401 Unauthorized** trying to call _auth/me_ endpoint after logging in. Maybe it's best for the error **“jwksError: Not Found”** to be logged, because it wasn't obvious this was the problem. For reference: [solution](https://community.auth0.com/t/solved-jwkserror-not-found-thrown-during-get-request-with-auth-bearer-token-to-protected-api/54734/2)

**Comment by DimiMikadze** [comment]
I'm happy to merge a PR if you have a solution for this.

**Comment by lowlyocean** [comment]
I think even just removing final "/" [here](https://github.com/DimiMikadze/fest/blob/1b17739d8c50c06efa5b14e1000f7ef92dbf4ca1/docs/auth0.md?plain=1#L15) would be good enough, since it documents clearer what format the Fest code expects
