### ISSUE TITLE
README does not mention POSTGRES_USER, POSTGRES_DB, and POSTGRES_PASSWORD 

### ISSUE THREAD

**Issue by lowlyocean** [DimiMikadze/fest#2]
These seem to be necessary in .env file in order for **docker-compose up** to work as expected, yet are not included in the template or instructions

**Comment by DimiMikadze** [comment]
Hi @lowlyocean , thanks for the issue. 

I think this bullet point in the readme explains that we need to update the environment variables: "Rename apps/api/.env.example to .env and apps/frontend/.env.local.example to .env.local and update environment variables." 

And those environment variables are in `.env.example` what do you think?

**Comment by lowlyocean** [comment]
Yeah, I agree - basically the solution is to just modify beginning of [this file ](https://github.com/DimiMikadze/fest/blob/main/apps/api/.env.example)as follows:
```
# PostgreSQL database URL
DATABASE_URL=postgresql://username:password@localhost:5432/postgres?schema=public
POSTGRES_DB=postgres
POSTGRES_USER=username
POSTGRES_PASSWORD=password
```
