### ISSUE TITLE
Database initialization not included in instructions

### ISSUE THREAD

**Issue by lowlyocean** [DimiMikadze/fest#3]
After following instructions from README,  navigating to **localhost:3000** triggers [this line ](https://github.com/DimiMikadze/fest/blob/1b17739d8c50c06efa5b14e1000f7ef92dbf4ca1/apps/api/src/auth/jwt.strategy.ts#L36)which produces following error (which suggests that some step in instructions is missing in order to initialize the database)

```
[Nest] 22180  - 01/03/2023, 3:27:40 PM   ERROR [ExceptionsHandler] 
Invalid `prisma.user.findUnique()` invocation:


The table `public.User` does not exist in the current database.
```

Update: From experimenting, it seems README should include that the following command is needed:
`yarn prisma:migrate:dev init`

**Comment by DimiMikadze** [comment]
Thank you, it looks like I missed that step. I'll add it in the readme.

**Comment by DimiMikadze** [comment]
https://github.com/DimiMikadze/fest/commit/016f60ed3813a9f06a9cceff017be6c20ff21d20
