### ISSUE TITLE
Default From address in Mail Service is hard-coded, causes Postmark warning

### ISSUE THREAD

**Issue by lowlyocean** [DimiMikadze/fest#4]
If you unknowingly leave [this line](https://github.com/DimiMikadze/fest/blob/95d5ed51e0dbee34ab00a7f27ff029319065306f/apps/api/src/mail/mail.service.ts#L23) as "no-reply@fest.dev", it will raise an error that this isn't a configured Sender Signature. It seems _no-reply_ is discouraged by Postmark.

Maybe instead make that line use `this.config.get('POSTMARK_SENDER')` and add POSTMARK_SENDER to the [example env file](https://github.com/DimiMikadze/fest/blob/95d5ed51e0dbee34ab00a7f27ff029319065306f/apps/api/.env.example)?

**Comment by DimiMikadze** [comment]
I agree that will be a better solution. Would you like to send a PR for it?
