### ISSUE TITLE
No example components showing Prisma interaction

### ISSUE THREAD

**Issue by lowlyocean** [DimiMikadze/fest#5]
Would be great for the children of <AppLayout> [here](https://github.com/DimiMikadze/fest/blob/95d5ed51e0dbee34ab00a7f27ff029319065306f/apps/frontend/pages/index.tsx#L13) to contain some example React component that reads/edits some data via Prisma.

**Comment by DimiMikadze** [comment]
Prisma is used in the API for database interaction. We can't directly interact with it from the frontend. We need to expose an API endpoint in the API so we can interact with it from the frontend using the `react-query` library. 

Examples of how to use the `react-query` library are in the `frontend/services` folder.
