### ISSUE TITLE
Lack of Billing/Subscriptions/Payments, or User Profile page

### ISSUE THREAD

**Issue by lowlyocean** [DimiMikadze/fest#6]
If this is meant to be a boilerplate or template for SaaS, I think it will be crucial to include Billing/Payments/Subscriptions page (e.g. via Stripe) as well as a user profile page. If you include these, then another benefit will be the example of navigation between pages.

**Comment by DimiMikadze** [comment]
I agree those features would be beneficial, but unfortunately, I don't have time to implement them. If you or somebody else wants to work on them, I'll be happy to review and merge those PRs.
